// Full expanded menu data for #hashtag Restaurant & Café
import drinkImg   from './assets/menu_drink.png';
import foodImg    from './assets/menu_food.png';
import dessertImg from './assets/menu_dessert.png';

export const menuCategories = [
  {
    id: 'hot-drinks',
    label: 'Hot Drinks',
    emoji: '☕',
    items: [
      { id: 'hd1',  name: 'Espresso',            price: '25 EGP',  desc: 'Double shot pure arabica espresso' },
      { id: 'hd2',  name: 'Americano',            price: '30 EGP',  desc: 'Espresso diluted with hot water, smooth & bold' },
      { id: 'hd3',  name: 'Cappuccino',           price: '45 EGP',  desc: 'Espresso, steamed milk and rich foam' },
      { id: 'hd4',  name: 'Flat White',           price: '50 EGP',  desc: 'Double ristretto with velvety micro-foam' },
      { id: 'hd5',  name: 'Latte',                price: '50 EGP',  desc: 'Silky steamed milk poured over espresso' },
      { id: 'hd6',  name: 'Mocha',                price: '55 EGP',  desc: 'Espresso, chocolate sauce & steamed milk' },
      { id: 'hd7',  name: 'Caramel Macchiato',    price: '55 EGP',  desc: 'Espresso layered with caramel & foam' },
      { id: 'hd8',  name: 'Hazelnut Latte',       price: '55 EGP',  desc: 'Roasted hazelnut syrup with espresso & milk' },
      { id: 'hd9',  name: 'Turkish Coffee',       price: '30 EGP',  desc: 'Traditional thick-brewed coffee with cardamom' },
      { id: 'hd10', name: 'Nescafé',              price: '25 EGP',  desc: 'Classic instant coffee with milk & sugar' },
      { id: 'hd11', name: 'Hot Chocolate',        price: '50 EGP',  desc: 'Rich Belgian chocolate melted in warm milk' },
      { id: 'hd12', name: 'Matcha Latte',         price: '60 EGP',  desc: 'Japanese ceremonial matcha with oat milk' },
    ],
    img: drinkImg,
  },
  {
    id: 'cold-drinks',
    label: 'Cold Drinks',
    emoji: '🧋',
    items: [
      { id: 'cd1',  name: 'Iced Latte',           price: '55 EGP',  desc: 'Espresso over ice with cold milk' },
      { id: 'cd2',  name: 'Iced Caramel Latte',   price: '60 EGP',  desc: 'Iced latte drizzled with salted caramel' },
      { id: 'cd3',  name: 'Cold Brew',            price: '55 EGP',  desc: '18-hour cold-steeped arabica — no bitterness' },
      { id: 'cd4',  name: 'Frappuccino',          price: '65 EGP',  desc: 'Blended iced coffee with whipped cream' },
      { id: 'cd5',  name: 'Iced Matcha',          price: '65 EGP',  desc: 'Ceremonial matcha blended over ice' },
      { id: 'cd6',  name: 'Iced Mocha',           price: '65 EGP',  desc: 'Chocolate-espresso bliss over crushed ice' },
      { id: 'cd7',  name: 'Oreo Frappe',          price: '70 EGP',  desc: 'Crushed Oreos blended with coffee & cream' },
      { id: 'cd8',  name: 'Lotus Frappe',         price: '70 EGP',  desc: 'Lotus Biscoff cream blended with cold coffee' },
      { id: 'cd9',  name: 'Bubble Tea (Taro)',    price: '75 EGP',  desc: 'Creamy taro with tapioca pearls' },
      { id: 'cd10', name: 'Bubble Tea (Matcha)',  price: '75 EGP',  desc: 'Matcha milk tea with tapioca pearls' },
    ],
    img: drinkImg,
  },
  {
    id: 'juices',
    label: 'Juices & Smoothies',
    emoji: '🥤',
    items: [
      { id: 'j1',  name: 'Fresh Orange Juice',   price: '45 EGP',  desc: 'Freshly squeezed Egyptian oranges' },
      { id: 'j2',  name: 'Mango Smoothie',       price: '55 EGP',  desc: 'Fresh mango blended with honey & yogurt' },
      { id: 'j3',  name: 'Berry Blast',          price: '60 EGP',  desc: 'Strawberry, blueberry & raspberry blend' },
      { id: 'j4',  name: 'Green Detox',          price: '60 EGP',  desc: 'Spinach, cucumber, apple, ginger & lemon' },
      { id: 'j5',  name: 'Banana Protein',       price: '60 EGP',  desc: 'Banana, peanut butter, almond milk & whey' },
      { id: 'j6',  name: 'Watermelon Mint',      price: '45 EGP',  desc: 'Fresh watermelon with spearmint & lime' },
      { id: 'j7',  name: 'Avocado Shake',        price: '65 EGP',  desc: 'Premium avocado with honey & coconut milk' },
      { id: 'j8',  name: 'Passion Fruit Cooler', price: '55 EGP',  desc: 'Passion fruit, mango & sparkling water' },
    ],
    img: drinkImg,
  },
  {
    id: 'breakfast',
    label: 'Breakfast',
    emoji: '🥞',
    items: [
      { id: 'b1',  name: 'Full English',         price: '120 EGP', desc: 'Eggs, beef sausage, beans, mushroom, toast' },
      { id: 'b2',  name: 'Eggs Benedict',        price: '110 EGP', desc: 'Poached eggs, hollandaise on English muffin' },
      { id: 'b3',  name: 'Avocado Toast',        price: '95 EGP',  desc: 'Sourdough, smashed avocado, poached egg, chilli' },
      { id: 'b4',  name: 'Shakshuka',            price: '85 EGP',  desc: 'Spiced tomato sauce with baked eggs & feta' },
      { id: 'b5',  name: 'Pancake Stack',        price: '90 EGP',  desc: '4 fluffy buttermilk pancakes with maple syrup' },
      { id: 'b6',  name: 'French Toast',         price: '85 EGP',  desc: 'Brioche dipped in custard, served with berries' },
      { id: 'b7',  name: 'Granola Bowl',         price: '75 EGP',  desc: 'Greek yogurt, homemade granola & seasonal fruit' },
      { id: 'b8',  name: 'Croissant Sandwich',   price: '80 EGP',  desc: 'Butter croissant with turkey, cheese & egg' },
    ],
    img: foodImg,
  },
  {
    id: 'salads',
    label: 'Salads',
    emoji: '🥗',
    items: [
      { id: 's1',  name: 'Caesar Salad',         price: '85 EGP',  desc: 'Romaine, parmesan, croutons, caesar dressing' },
      { id: 's2',  name: 'Greek Salad',          price: '80 EGP',  desc: 'Tomato, cucumber, olives, feta, red onion' },
      { id: 's3',  name: 'Quinoa Bowl',          price: '95 EGP',  desc: 'Quinoa, roasted veg, chickpea, tahini drizzle' },
      { id: 's4',  name: 'Rocket & Parmesan',   price: '90 EGP',  desc: 'Wild rocket, shaved parmesan, lemon dressing' },
      { id: 's5',  name: 'Tuna Niçoise',         price: '100 EGP', desc: 'Tuna, egg, olives, green beans, mustard vin.' },
      { id: 's6',  name: 'Fattoush',             price: '70 EGP',  desc: 'Toasted pita, fresh veg, sumac & pomegranate' },
    ],
    img: foodImg,
  },
  {
    id: 'burgers',
    label: 'Burgers & Sandwiches',
    emoji: '🍔',
    items: [
      { id: 'bu1', name: 'Classic Smash Burger', price: '130 EGP', desc: 'Double smashed beef patty, American cheese, pickles' },
      { id: 'bu2', name: 'BBQ Burger',           price: '145 EGP', desc: 'Beef patty, BBQ sauce, crispy onion, cheddar' },
      { id: 'bu3', name: 'Truffle Mushroom',     price: '155 EGP', desc: 'Beef patty, sautéed mushrooms, truffle aioli' },
      { id: 'bu4', name: 'Crispy Chicken',       price: '120 EGP', desc: 'Crispy fried chicken, slaw, sriracha mayo' },
      { id: 'bu5', name: 'Club Sandwich',        price: '110 EGP', desc: 'Turkey, beef bacon, egg, cheese, triple toast' },
      { id: 'bu6', name: 'Philly Cheese Steak', price: '140 EGP', desc: 'Shaved ribeye, peppers, onions, provolone' },
      { id: 'bu7', name: 'Pulled Beef Wrap',    price: '115 EGP', desc: 'Slow-cooked beef, coleslaw, chipotle in a wrap' },
      { id: 'bu8', name: 'Veggie Burger',        price: '105 EGP', desc: 'Chickpea & beetroot patty, avocado, tahini' },
    ],
    img: foodImg,
  },
  {
    id: 'pasta-rice',
    label: 'Pasta & Rice',
    emoji: '🍝',
    items: [
      { id: 'p1',  name: 'Penne Arrabbiata',     price: '110 EGP', desc: 'Spicy tomato sauce, garlic, fresh basil' },
      { id: 'p2',  name: 'Fettuccine Alfredo',   price: '125 EGP', desc: 'Creamy parmesan sauce with fresh pasta' },
      { id: 'p3',  name: 'Spaghetti Bolognese',  price: '130 EGP', desc: 'Slow-cooked beef ragu, san marzano tomato' },
      { id: 'p4',  name: 'Mushroom Risotto',     price: '120 EGP', desc: 'Arborio rice, porcini, truffle oil, parmesan' },
      { id: 'p5',  name: 'Shrimp Pasta',         price: '145 EGP', desc: 'Shrimp, garlic butter, cherry tomato, linguine' },
      { id: 'p6',  name: 'Grilled Chicken Rice', price: '115 EGP', desc: 'Herb rice, grilled chicken, grilled veg, sauce' },
    ],
    img: foodImg,
  },
  {
    id: 'grills',
    label: 'Grills & Mains',
    emoji: '🥩',
    items: [
      { id: 'g1',  name: 'Grilled Ribeye 250g',  price: '320 EGP', desc: 'Aged ribeye, herb butter, garlic mash & asparagus' },
      { id: 'g2',  name: 'Grilled Chicken',      price: '150 EGP', desc: 'Marinated chicken breast, chimichurri, fries' },
      { id: 'g3',  name: 'Mixed Grill Platter',  price: '280 EGP', desc: 'Kofta, chicken, shish, served with rice & salad' },
      { id: 'g4',  name: 'Grilled Salmon',       price: '220 EGP', desc: 'Atlantic salmon, lemon butter, capers, quinoa' },
      { id: 'g5',  name: 'Chicken Tikka',        price: '160 EGP', desc: 'Tandoor-marinated chicken with naan & raita' },
      { id: 'g6',  name: 'Grilled Shrimp',       price: '195 EGP', desc: 'Jumbo shrimp, garlic, lemon, herbs, couscous' },
    ],
    img: foodImg,
  },
  {
    id: 'desserts',
    label: 'Desserts',
    emoji: '🍰',
    items: [
      { id: 'ds1', name: 'Chocolate Lava Cake',  price: '75 EGP',  desc: 'Warm valrhona center, vanilla ice cream' },
      { id: 'ds2', name: 'Crème Brûlée',         price: '70 EGP',  desc: 'Classic French vanilla custard, caramelized top' },
      { id: 'ds3', name: 'Tiramisu',             price: '80 EGP',  desc: 'Mascarpone, espresso-soaked savoiardi, cocoa' },
      { id: 'ds4', name: 'Lotus Cheesecake',     price: '85 EGP',  desc: 'Baked Biscoff cheesecake, lotus crumble base' },
      { id: 'ds5', name: 'Nutella Waffle',       price: '75 EGP',  desc: 'Belgian waffle, Nutella, banana, crushed hazelnuts' },
      { id: 'ds6', name: 'Kunafa',               price: '70 EGP',  desc: 'Traditional shredded pastry with cheese & syrup' },
      { id: 'ds7', name: 'Ice Cream (3 scoops)', price: '60 EGP',  desc: 'Choice of 3 flavours from our daily rotation' },
      { id: 'ds8', name: 'Baklava Plate',        price: '65 EGP',  desc: 'Assorted baklava with pistachio, honey & rose water' },
    ],
    img: dessertImg,
  },
];
